diff -Naupr atop-2.6.0-orig/Makefile atop-2.6.0/Makefile
--- atop-2.6.0-orig/Makefile	2020-12-21 20:57:55.000000000 +0100
+++ atop-2.6.0/Makefile	2020-12-24 09:37:17.301956332 +0100
@@ -6,15 +6,14 @@ DESTDIR  =
 
 BINPATH  = /usr/bin
 SBINPATH = /usr/sbin
-SCRPATH  = /usr/share/atop
 LOGPATH  = /var/log/atop
-MAN1PATH = /usr/share/man/man1
-MAN5PATH = /usr/share/man/man5
-MAN8PATH = /usr/share/man/man8
-INIPATH  = /etc/init.d
+MAN1PATH = /usr/man/man1
+MAN5PATH = /usr/man/man5
+MAN8PATH = /usr/man/man8
+INIPATH  = /etc/rc.d
 DEFPATH  = /etc/default
 SYSDPATH = /lib/systemd/system
-CRNPATH  = /etc/cron.d
+DAYPATH  = /etc/cron.daily
 ROTPATH  = /etc/logrotate.d
 PMPATH1  = /usr/lib/pm-utils/sleep.d
 PMPATH2  = /usr/lib64/pm-utils/sleep.d
@@ -91,18 +90,15 @@ systemdinstall:	genericinstall
 sysvinstall:	genericinstall
 		if [ ! -d $(DESTDIR)$(INIPATH) ]; 			\
 		then	mkdir -p  $(DESTDIR)$(INIPATH);	fi
-		if [ ! -d $(DESTDIR)$(SCRPATH) ]; 			\
-		then	mkdir -p $(DESTDIR)$(SCRPATH);	fi
-		if [ ! -d $(DESTDIR)$(CRNPATH) ]; 			\
-		then	mkdir -p $(DESTDIR)$(CRNPATH);	fi
+		if [ ! -d $(DESTDIR)$(DAYPATH) ]; 			\
+		then	mkdir -p $(DESTDIR)$(DAYPATH);	fi
 		if [ ! -d $(DESTDIR)$(ROTPATH) ]; 			\
 		then	mkdir -p $(DESTDIR)$(ROTPATH);	fi
 		#
-		cp atop.init      $(DESTDIR)$(INIPATH)/atop
-		cp atopacct.init  $(DESTDIR)$(INIPATH)/atopacct
-		cp atop.cronsysv  $(DESTDIR)$(CRNPATH)/atop
-		cp atop.daily     $(DESTDIR)$(SCRPATH)
-		chmod 0711        $(DESTDIR)$(SCRPATH)/atop.daily
+		cp atop.init      $(DESTDIR)$(INIPATH)/rc.atop
+		cp atopacct.init  $(DESTDIR)$(INIPATH)/rc.atopacct
+		cp atop.daily     $(DESTDIR)$(DAYPATH)
+		chmod 0711        $(DESTDIR)$(DAYPATH)/atop.daily
 		cp psaccs_atop    $(DESTDIR)$(ROTPATH)/psaccs_atop
 		cp psaccu_atop    $(DESTDIR)$(ROTPATH)/psaccu_atop
 		touch             $(DESTDIR)$(LOGPATH)/dummy_before
