.TH POKERTH "1" "March 2008" "PokerTH server 0.6.1" "User Commands"
.SH NAME
pokerth_server \- multiplayer and multigame server for PokerTH
.SH SYNOPSIS
.B pokerth_server \fR[ \fB\-h\fR | \fB\-\-help\fR ] [ \fB\-v\fR | \fB\-\-version\fR ]
[ \fB\-p\fR | \fB\-\-pid\-file\fR\fI pid-file \fR] [ \fB\-\-readonly\-config\fR ]
.SH DESCRIPTION
This is the PokerTH server, which is needed for hosting own multiplayer games.
Network protocol version 4.1
.SH OPTIONS
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
produce help message
.TP
\fB\-v\fR [ \fB\-\-version\fR ]
print version string
.TP
\fB\-p\fR [ \fB\-\-pid\-file\fR ] \fIpid-file\fR
create pid\-file in different location
.TP
\fB\-\-readonly\-config\fR
treat config file as read\-only
.SH AUTHOR
pokerth and pokerth_server were written by Felix Hammer, Florian Thauer and Lothar May.
.PP
This manual page was written by Evgeni Golov <sargentd@die-welt.net>,
for the Debian project (but may be used by others).
