diff -Naupr hwinfo-21.12-orig/Makefile hwinfo-21.12/Makefile
--- hwinfo-21.12-orig/Makefile	2015-02-27 10:26:03.000000000 +0100
+++ hwinfo-21.12/Makefile	2015-05-24 08:50:36.000000000 +0200
@@ -1,8 +1,8 @@
 TOPDIR		= $(CURDIR)
 SUBDIRS		= src
-TARGETS		= hwinfo hwinfo.pc changelog
-CLEANFILES	= hwinfo hwinfo.pc hwinfo.static hwscan hwscan.static hwscand hwscanqueue doc/libhd doc/*~
-LIBDIR		= /usr/lib
+TARGETS		= hwinfo hwinfo.pc
+CLEANFILES	= hwinfo hwinfo.pc hwinfo.static hwscan hwscan.static hwscand hwscanqueue doc/libhd doc/*~ VERSION
+LIBDIR		?= /usr/lib
 ULIBDIR		= $(LIBDIR)
 LIBS		= -lhd
 SLIBS		= -lhd
@@ -12,10 +12,8 @@ TSO_LIBS	=
 
 export SO_LIBS
 
-GIT2LOG := $(shell if [ -x ./git2log ] ; then echo ./git2log --update ; else echo true ; fi)
-GITDEPS := $(shell [ -d .git ] && echo .git/HEAD .git/refs/heads .git/refs/tags)
-VERSION := $(shell $(GIT2LOG) --version VERSION ; cat VERSION)
-BRANCH  := $(shell git branch | perl -ne 'print $$_ if s/^\*\s*//')
+VERSION := $(shell cat VERSION)
+# BRANCH  := $(shell git branch | perl -ne 'print $$_ if s/^\*\s*//')
 PREFIX  := hwinfo-$(VERSION)
 
 include Makefile.common
@@ -33,20 +31,17 @@ OBJS_NO_TINY	= names.o parallel.o modem.
 
 .PHONY:	fullstatic static shared tiny doc diet tinydiet uc tinyuc
 
-changelog: $(GITDEPS)
-	$(GIT2LOG) --changelog changelog
-
 hwscan: hwscan.o $(LIBHD)
-	$(CC) hwscan.o $(LDFLAGS) $(LIBS) -o $@
+	$(CC) hwscan.o $(LDFLAGS) $(CFLAGS) $(LIBS) -o $@
 
 hwinfo: hwinfo.o $(LIBHD)
-	$(CC) hwinfo.o $(LDFLAGS) $(LIBS) -o $@
+	$(CC) hwinfo.o $(LDFLAGS) $(CFLAGS) $(LIBS) -o $@
 
 hwscand: hwscand.o
-	$(CC) $< $(LDFLAGS) -o $@
+	$(CC) $< $(LDFLAGS) $(CFLAGS) -o $@
 
 hwscanqueue: hwscanqueue.o
-	$(CC) $< $(LDFLAGS) -o $@
+	$(CC) $< $(LDFLAGS) $(CFLAGS) -o $@
 
 hwinfo.pc: hwinfo.pc.in VERSION
 	VERSION=`cat VERSION`; \
