diff -Naupr a/Makefile b/Makefile
--- a/Makefile	2019-08-25 19:32:03.000000000 +0200
+++ b/Makefile	2019-08-30 10:35:35.404894514 +0200
@@ -52,7 +52,7 @@ bup_cmds := cmd/bup-python\
 
 bup_deps := bup lib/bup/_checkout.py lib/bup/_helpers$(SOEXT) $(bup_cmds)
 
-all: $(bup_deps) Documentation/all $(current_sampledata)
+all: $(bup_deps) $(current_sampledata)
 
 bup:
 	ln -s main.py bup
@@ -70,18 +70,6 @@ define install-python-bin
   chmod 0755 $(2);
 endef
 
-PANDOC ?= $(shell type -p pandoc)
-
-ifeq (,$(PANDOC))
-  $(shell echo "Warning: pandoc not found; skipping manpage generation" 1>&2)
-  man_md :=
-else
-  man_md := $(wildcard Documentation/*.md)
-endif
-
-man_roff := $(patsubst %.md,%.1,$(man_md))
-man_html := $(patsubst %.md,%.html,$(man_md))
-
 INSTALL=install
 PREFIX=/usr/local
 MANDIR=$(PREFIX)/share/man
@@ -225,42 +213,6 @@ cmd/bup-%: cmd/%-cmd.sh
 	rm -f $@
 	ln -s $*-cmd.sh $@
 
-.PHONY: Documentation/all
-Documentation/all: $(man_roff) $(man_html)
-
-Documentation/substvars: $(bup_deps)
-	echo "s,%BUP_VERSION%,$$(./bup version --tag),g" > $@
-	echo "s,%BUP_DATE%,$$(./bup version --date),g" >> $@
-
-Documentation/%.1: Documentation/%.md Documentation/substvars
-	$(pf); sed -f Documentation/substvars $< \
-	  | $(PANDOC) -s -r markdown -w man -o $@
-
-Documentation/%.html: Documentation/%.md Documentation/substvars
-	$(pf); sed -f Documentation/substvars $< \
-	  | $(PANDOC) -s -r markdown -w html -o $@
-
-.PHONY: Documentation/clean
-Documentation/clean:
-	cd Documentation && rm -f *~ .*~ *.[0-9] *.html substvars
-
-# Note: this adds commits containing the current manpages in roff and
-# html format to the man and html branches respectively.  The version
-# is determined by "git describe --always".
-.PHONY: update-doc-branches
-update-doc-branches: Documentation/all
-	dev/update-doc-branches refs/heads/man refs/heads/html
-
-# push the pregenerated doc files to origin/man and origin/html
-push-docs: export-docs
-	git push origin man html
-
-# import pregenerated doc files from origin/man and origin/html, in case you
-# don't have pandoc but still want to be able to install the docs.
-import-docs: Documentation/clean
-	$(pf); git archive origin/html | (cd Documentation && tar -xvf -)
-	$(pf); git archive origin/man | (cd Documentation && tar -xvf -)
-
 clean: Documentation/clean cmd/bup-python
 	cd config && rm -f *~ .*~ \
 	  ${CONFIGURE_DETRITUS} ${CONFIGURE_FILES} ${GENERATED_FILES}
