if [ -x usr/bin/update-desktop-database ]; then
  usr/bin/update-desktop-database -q usr/share/applications/kde
fi

( cd usr/lib64 ; rm -rf libkexiv2.so.11 )
( cd usr/lib64 ; ln -sf libkexiv2.so.11.3.0 libkexiv2.so.11 )
( cd usr/lib64 ; rm -rf libkface.so.3 )
( cd usr/lib64 ; ln -sf libkface.so.3.0.0 libkface.so.3 )
( cd usr/lib64 ; rm -rf libkface.so )
( cd usr/lib64 ; ln -sf libkface.so.3 libkface.so )
( cd usr/lib64 ; rm -rf libksane.so.0 )
( cd usr/lib64 ; ln -sf libksane.so.0.2.0 libksane.so.0 )
( cd usr/lib64 ; rm -rf libkipi.so.11 )
( cd usr/lib64 ; ln -sf libkipi.so.11.1.0 libkipi.so.11 )
( cd usr/lib64 ; rm -rf libkexiv2.so )
( cd usr/lib64 ; ln -sf libkexiv2.so.11 libkexiv2.so )
( cd usr/lib64 ; rm -rf libmediawiki.so )
( cd usr/lib64 ; ln -sf libmediawiki.so.1 libmediawiki.so )
( cd usr/lib64 ; rm -rf libkdcraw.so )
( cd usr/lib64 ; ln -sf libkdcraw.so.23 libkdcraw.so )
( cd usr/lib64 ; rm -rf libkipi.so )
( cd usr/lib64 ; ln -sf libkipi.so.11 libkipi.so )
( cd usr/lib64 ; rm -rf libkgeomap.so.2 )
( cd usr/lib64 ; ln -sf libkgeomap.so.2.1.0 libkgeomap.so.2 )
( cd usr/lib64 ; rm -rf libmediawiki.so.1 )
( cd usr/lib64 ; ln -sf libmediawiki.so.1.0.0 libmediawiki.so.1 )
( cd usr/lib64 ; rm -rf libkipiplugins.so )
( cd usr/lib64 ; ln -sf libkipiplugins.so.4.10.0 libkipiplugins.so )
( cd usr/lib64 ; rm -rf libdigikamcore.so )
( cd usr/lib64 ; ln -sf libdigikamcore.so.4.10.0 libdigikamcore.so )
( cd usr/lib64 ; rm -rf libkdcraw.so.23 )
( cd usr/lib64 ; ln -sf libkdcraw.so.23.0.0 libkdcraw.so.23 )
( cd usr/lib64 ; rm -rf libdigikamdatabase.so )
( cd usr/lib64 ; ln -sf libdigikamdatabase.so.4.10.0 libdigikamdatabase.so )
( cd usr/lib64 ; rm -rf libkgeomap.so )
( cd usr/lib64 ; ln -sf libkgeomap.so.2 libkgeomap.so )
( cd usr/lib64 ; rm -rf libksane.so )
( cd usr/lib64 ; ln -sf libksane.so.0 libksane.so )
( cd usr/doc/HTML/en/digikam ; rm -rf common )
( cd usr/doc/HTML/en/digikam ; ln -sf /usr/doc/HTML/en/common common )
( cd usr/doc/HTML/en/showfoto ; rm -rf common )
( cd usr/doc/HTML/en/showfoto ; ln -sf /usr/doc/HTML/en/common common )
( cd usr/doc/HTML/en/kipi-plugins ; rm -rf common )
( cd usr/doc/HTML/en/kipi-plugins ; ln -sf /usr/doc/HTML/en/common common )
( cd usr/doc/HTML/it/digikam ; rm -rf common )
( cd usr/doc/HTML/it/digikam ; ln -sf /usr/doc/HTML/it//common common )
( cd usr/doc/HTML/pt/digikam ; rm -rf common )
( cd usr/doc/HTML/pt/digikam ; ln -sf /usr/doc/HTML/pt//common common )
( cd usr/doc/HTML/pt_BR/digikam ; rm -rf common )
( cd usr/doc/HTML/pt_BR/digikam ; ln -sf /usr/doc/HTML/pt_BR//common common )
( cd usr/doc/HTML/nl/digikam ; rm -rf common )
( cd usr/doc/HTML/nl/digikam ; ln -sf /usr/doc/HTML/nl//common common )
( cd usr/doc/HTML/uk/digikam ; rm -rf common )
( cd usr/doc/HTML/uk/digikam ; ln -sf /usr/doc/HTML/uk//common common )
( cd usr/doc/HTML/sv/digikam ; rm -rf common )
( cd usr/doc/HTML/sv/digikam ; ln -sf /usr/doc/HTML/sv//common common )
