#!/bin/sh
#
# Slackware build script for sqlmap
#
# Copyright 2016 Corrado Franco (http://conraid.net)
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version, with the following exception:
# the text of the GPL license may be omitted.

# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of
# merchantability or fitness for a particular purpose. Compiling,
# interpreting, executing or merely reading the text of the program
# may result in lapses of consciousness and/or very being, up to and
# including the end of all existence and the Universe as we know it.
# See the GNU General Public License for more details.

# You may have received a copy of the GNU General Public License along
# with this program (most likely, a file named COPYING).  If not, see
# <http://www.gnu.org/licenses/>.
#
# Latest version of this SlackBuild at https://github.com/conraid/SlackBuilds

set -eu

CWD=$(pwd)

PRGNAM=sqlmap
VERSION=${VERSION:-1.0.4}
BUILD=${BUILD:-1}
TAG=${TAG:-cf}
TMP=${TMP:-/tmp/pkg}
PKG=$TMP/package-$PRGNAM

DOCFILES="README*"

if [ -z ${ARCH:=""} ]; then
  case "$( uname -m )" in
  i?86) ARCH=i686 ;;
  arm*) ARCH=arm ;;
     *) ARCH=$( uname -m ) ;;
  esac
fi
[ "$ARCH" = "x86_64" ] && LIBDIRSUFFIX="64" || LIBDIRSUFFIX=""

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz || tar xvf $CWD/v$VERSION.tar.gz
cd $PRGNAM-$VERSION

chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

python2 -m compileall .
python2 -O -m compileall .

mkdir -p $PKG/usr/share/$PRGNAM
mkdir -p $PKG/etc
mkdir -p $PKG/usr/bin
mkdir -p $PKG/usr/doc/

cat << EOF > $PKG/usr/bin/$PRGNAM
#!/bin/sh
cd /usr/share/$PRGNAM
python sqlmap.py "\$@"
EOF
chmod 755 $PKG/usr/bin/$PRGNAM

mv doc $PKG/usr/doc/$PRGNAM-$VERSION
mv sqlmap.conf $PKG/etc/sqlmap.conf.new
ln -sf /etc/sqlmap.conf $PKG/usr/share/$PRGNAM/sqlmap.conf
cp -a * $PKG/usr/share/$PRGNAM

cp -a $DOCFILES $PKG/usr/doc/$PRGNAM-$VERSION || true
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install 
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
