m4_define([AT_PACKAGE_NAME],[firewalld])
m4_define([AT_PACKAGE_VERSION],[2.1.0])
m4_define([AT_PACKAGE_STRING],[firewalld 2.1.0])
m4_define([AT_PACKAGE_URL],[http://firewalld.org/])
m4_define([AT_PACKAGE_BUGREPORT],[https://github.com/firewalld/firewalld])
